### PR TITLE
Update mode for install script

### PR DESCRIPTION
**Pull request by purpleidea**
It should have the executable bit set so it can be run more easily.

### CODE REVIEW

**Review by Anonymousdog — COMMENTED** [review]
This is not supported on GitHub: Setting file mode on POSIX-compliant file systems.

**Comment by purpleidea** [comment]
This kind of patch is supported on github... You can see in the diff. Or maybe I misunderstood what you were saying?

**Comment by Anonymousdog** [comment]
Where do you see in GitHub, the ability to set POSIX modes on files in the
repo?

**Comment by purpleidea** [comment]
On Thu, Feb 17, 2022 at 12:45 PM Anonymousdog ***@***.***> wrote:
>
> Where do you see in GitHub, the ability to set POSIX modes on files in the
> repo?

I did it in my terminal and pushed it. I don't know how to do it in
the github UI. But the Github UI can see the change and merge it. You
can see that if you look closely in the github diff for the PR I sent.

HTH

>

**Comment by Anonymousdog** [comment]
But that's relevant to almost nobody who uses the package. Only folks doing
a git sync (is what it sounds like you're describing re: "see the change")
to a POSIX file system would see the change. Literally everyone else would
have to change the executable bit on the installer script on their local
file systems, right? I don't think POSIX mode is even a supported zip file
system file attribute. I don't have this repo git synced to a POSIX file
system, and the whole project is EOL due to omxplayer's being deprecated.
Correct me if I'm wrong about the above because, otherwise, I don't see the
value.

**Comment by purpleidea** [comment]
On Thu, Feb 17, 2022 at 2:38 PM Anonymousdog ***@***.***> wrote:
>
> But that's relevant to almost nobody who uses the package. Only folks doing
> a git sync (is what it sounds like you're describing re: "see the change")
> to a POSIX file system would see the change. Literally everyone else would
> have to change the executable bit on the installer script on their local
> file systems, right? I don't think POSIX mode is even a supported zip file
> system file attribute. I don't have this repo git synced to a POSIX file
> system, and the whole project is EOL due to omxplayer's being deprecated.
> Correct me if I'm wrong about the above because, otherwise, I don't see the
> value.

Anyone cloning and using the package will appreciate the small change.
It's small but correct.
Cheers

>

**Pull request closed without merging**
